[feat] get chatting message API / API Docs
Team-Crops/fit-server pull request #54
Opened 2024-04-15 13:36 UTC by SeorinY

## 🥔 작업한 내용

 - 채팅 리스트 조회 api 추가
 - controller test + API Docs 추가

## ❗️ PR POINT

- 아직 유저 -> 방 로직 검증은 미구현 입니다!! 금방 수정할 수 있는 부분이라서 우선 비웠습니다! 

## 🔒 관련 이슈

2024-04-15 13:45 UTC, junchanpp requested changes
확인부탁드려요

2024-04-15 13:45 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/MessageController.java
> +public class MessageController {
기존 chat 도메인과 유사한 형태를 하면 좋을 거 같아요. 같은 db를 무조건 바라볼텐데 도메인이 나누는게 맞는지 궁금해요

2024-04-15 13:45 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/dto/MessageDto.java
> +) {
보낸 시간도 있어야 하지 않을까요?
그리고 구현사항 중에서 유저가 마지막으로 확인한 위치부터 보여주는 것으로 알고 있는데,
messageId같은 것도 포함되면 좋을 거 같아요 지금 당장 구현하지 않더라도...

2024-04-15 13:45 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/facade/impl/MessageFacadeImpl.java
> +        .collect(Collectors.toList());
그냥 toList()하면 좋을 거 같아요

2024-04-15 13:45 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/repository/MessageRepository.java
> +      + "order by m.createdAt desc")
사용자에게 보여줄 때는 생성일자 내림 차순이 아니라 생성일자 오름차순 아닐까요?
스크롤이 위로 가서 방향때문에 헷갈린 거 같은데 프론트에서 그려줄때에는 위에서 아래로 그려주기때문에 위에서 아래로 생성일자 오름차순이 되어야 할 거 같아요

2024-04-15 14:02 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/controller/MessageController.java
> +public class MessageController {
ChatController ->  @SocketController는 Custum Annotation 으로 Socket Server 에 올라가는 객체여서 
Restful Api 처리하는 핸들러 함수는 정의해주지 않으려고  MessageController 를 따로 만들었습니다!

@SocketController 가 달린 Controller는  ChatSocketControlle 이런 식으로 이름을 변경하고
위의 객체는 @RestController 가 달린 ChatController 로 이름을 변경할까요?

2024-04-15 14:02 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/dto/MessageDto.java
> +) {
헉! 놓쳤군요 
바로 추가하겠숨다

2024-04-15 14:03 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/facade/impl/MessageFacadeImpl.java
> +        .collect(Collectors.toList());
Collectors static import 말하시는 거 맞나요?

2024-04-15 14:03 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/MessageController.java
> +public class MessageController {
넵 제가 말한 게 그게 맞습니다~

2024-04-15 14:03 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/repository/MessageRepository.java
> +      + "order by m.createdAt desc")
아하 그 카카오톡처럼 생각했는데 
이거 회의 때 애기해보겠습니당

2024-04-15 14:04 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/facade/impl/MessageFacadeImpl.java
> +        .collect(Collectors.toList());
```suggestion
        .toList();
```
말한겁니다!

2024-04-15 14:36 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/repository/MessageRepository.java
> +      + "order by m.createdAt desc")
그리고 createdAt보다 messageId가 더 나을거 같아요! createdAt 중복가능성이 있어서 정렬이 마음대로 안될수도 있어요. 또한 인덱스 처리가 필요할텐데 성능 낭비인 거 같아요.

2024-04-28 23:38 UTC, junchanpp reviewed
확인 부탁드립니다.

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/dto/MessageDto.java
> +) {
MessageResponse를 사용하지 않고 따로 만든 이유가 있나요??
socket에서의 응답과 rest api에서의 응답이 똑같을 거 같은데 다시 만든 이유가 궁금합니다.

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +  public ResponseEntity<MessageIdResponse> getRecentMessages(
recent는 불분명한 것 같습니다.
처음 읽었을 때에는 가장 최근 메시지를 가져올 거 같았습니다.
로직을 확인해보니, 유저가 마지막으로 확인한 messageId를 가져오는 거 같더라고요.
좀 더 분명한 이름으로 수정되면 좋을 거 같아요.
추가로 id를 가져오는 api인데 message's'는 아닌 거 같네요.

그리고 위 메서드와 이 메서드에서의 response를 생성하는 정적 팩토리 메서드의 네이밍이 다르네요. 
둘 다 한 객체만 파라미터로 받는데, 통일하면 좋을 거 같아요.

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +    var response = MessageIdResponse.from(
MessageIdResponse라는 이름이 기능 확대가 될 때 조금 걸림돌이 될 거 같습니다. 좀 더 범용적인 이름이 좋을 거 같아요.

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/dto/request/ReceiveMessageRequest.java
> +    @NotNull long messageId
원시타입에 NotNull이 의미가 있나요?

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/dto/response/GetMessageListResponse.java
> +    CursorResult<MessageDto> cursorResult
이름이 수정되면 좋을 거 같아요.
프론트 입장에서 cursorResult라는 이름이 중요하지 않을 거 같아요.

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/facade/ChatRoomFacade.java
> +      Long lastMessageId);
여기서 lastMessageId가 다른 타입과 잘 구별이 안되는데,
Optional(Long)으로 하는 건 어떨까요?

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
> +  }
지금 생각해보니, 해당 로직은 실제로 유저가 조회하지 않았는데, 조회했다고 쿼리될 가능성이 있을 거 같습니다.
또한 프로젝트 모음에서는 채팅 리스트가 보이지만, 소켓으로는 연결이 되지 않는 것을 고려했을 때 제대로 update가 안될 수 있을 거 같습니다.
get messageList rest api에서 수정하는 것이 좋아보여요.

그리고 상위 메서드에서 transaction을 걸어도 하위 메서드에서 transaction을 거는 편이 좋아보입니다!

2024-04-28 23:38 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
> +        .orElseGet(() -> ChatRoomUser.create(user, room));
해당 로직으로 인해 잘못된 사용자가 chatRoom에 가입될 가능성이 있을 거 같습니다. 여기서 가입을 처리하는 것이 아닌, 채팅방에 가입이 될 때 create해주는 것이 좋을 거 같습니다.

2024-04-29 03:11 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/dto/MessageDto.java
> +) {
이거 저번에 소켓 통신할 때   Image, Notice, Text  용 Response dto 를 분리해서 하자고 했었어서
현재 Message Response 는 추상 클래스입니다!
그래서 그냥 따로 만들었는데 좀 더 좋은 방법이 있을까요?
MessageResponse 내부에서 타입을 검사해서 하위 타입들로 매칭 할 순 있는데  좋아보이는지는 모르겠습니다

2024-04-29 03:16 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +  public ResponseEntity<MessageIdResponse> getRecentMessages(
getLastCheckedMessage 
어떤가요?

2024-04-29 03:17 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +    var response = MessageIdResponse.from(
챗지피티가 추천해줬는데   뭔가 마땅한게 떠올르지않아서..
message id값만 갖는 응답 클래스로 어떤 이름이 좋을까요..

2024-04-29 04:09 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/dto/response/GetMessageListResponse.java
> +    CursorResult<MessageDto> cursorResult
다음 페이지 여부까지 있는 응답이니까  
PageResult 어떤가요?

2024-04-29 04:19 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/facade/ChatRoomFacade.java
> +      Long lastMessageId);
https://mangkyu.tistory.com/203

Optional 은  null 일 때  nullPointException 같은 에러가 날 확률이 높은 경우 사용하는 것이라고 알고 있습니당

Nullable 파라미터임을 강조하려고 Optional 하기에는 조금 불필요할 수도 있을 것 같다고 생각합니당
ps. 그리고 optional 은 가급적 파라미터로 넣지 말라네요!

2024-04-29 04:25 UTC, SeorinY commented on src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
> +        .orElseGet(() -> ChatRoomUser.create(user, room));
ChatRoomUser 를 그러면 
아예  채팅방 가입유저로 제한시키겠슴당

2024-04-29 04:31 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/dto/MessageDto.java
> +) {
따로 만드는 것보다 기존처럼 하는 게 나을 거 같아요.
똑같은 역할이고, 프론트가 볼 때 아예 똑같은 response인데,
관리 포인트가 늘어나는 것 같습니다.
한 번 구현해두면 두고두고 쓸 거 같네요.

2024-04-29 04:32 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +  public ResponseEntity<MessageIdResponse> getRecentMessages(
사용자 관점에서 좀 더 직관적인건 getLastSeenMessage 일 거 같습니다.

2024-04-29 04:34 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
> +    var response = MessageIdResponse.from(
messageId값만 갖는 응답 클래스라고 해서 이름을 단정지으면, 
멤버변수 단 하나에 종속되는 이름같습니다. 멤버변수와 상관없이 이름을 지으면 좋을 거 같아요.
메서드명과 유사하게 지으면 좋을 거 같아요.

2024-04-29 04:35 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/facade/ChatRoomFacade.java
> +      Long lastMessageId);
오 좋아요 감사합니다.

2024-04-29 04:36 UTC, junchanpp commented on src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
> +  }
기존에 있는 rest api에 코드 한줄 추가하면 좋을 거 같아요

2024-05-06 11:44 UTC, merged